### ISSUE TITLE
Link to authority files without prefix 

### ISSUE THREAD

**Issue by morethanbooks** [COST-ELTeC/ELTeC-ukr#2]
In general, the ELTeC corpora contain prefixes to the source of the authority files. Example with viaf and an author (https://raw.githubusercontent.com/COST-ELTeC/ELTeC-ukr/master/level1/UKR19022_KobylianskaZemlia.xml):
`<author ref="viaf:317288905">Кобилянська, Ольга (1863-1942)</author>`
However, in four texts, the titles are referenced without prefix. For example:
`<title ref="1323151965444500470002">Земля. Оповідання : ELTeC видання</title>`

I guess this link is also to viaf and it should be:
`<title ref="viaf:1323151965444500470002">Земля. Оповідання : ELTeC видання</title>`

This happens in following files: UKR19022, UKR19091, UKR19121, UKR19172.
Regards!

**Comment by lb42** [comment]
Thanks for reporting this! Added viaf: prefix to these four files.

**Comment by morethanbooks** [comment]
Thanks!
